# -*- coding: utf-8 -*-
"""chat_with_arxive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQPzqMW9qEJHRbqYNe2NPBlFPeCyfjf6
"""

pip install streamlit

pip install -U phidata

pip install openai

pip install pypdf

pip install arxiv

import streamlit as st

from phi.assistant import Assistant
from phi.llm.openai import OpenAIChat
from phi.tools.arxiv_toolkit import ArxivToolkit



st.title("chat with Arxiv")
st.caption("this app")

openai_access_token = st.text_input("openai API KEY", type='password')
if openai_access_token:
  assistant = Assistant(
      llm= OpenAIChat(
          model = "gpt-4o",
          max_tokens = 1024,
          temperature = 0.9,
          api_key=openai_access_token), tools = [ArxivToolkit()], show_tool_calls= True
  )

  qurey = st.text_input("enter the search Query", type="default")
  if query :
    response = Assistant.run(query, stream= False)
    st.write(response)